/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0GVWwk3lgGN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

export function Home() {
  return (
    (<div className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="flex items-center mb-6">
        <Input
          type="text"
          placeholder="Enter city name"
          className="flex-1 mr-4 h-10 rounded-md border-gray-300 focus:border-primary focus:ring-primary" />
        <Button className="h-10 rounded-md bg-primary text-primary-foreground">Search</Button>
      </div>
      <div className="bg-background border border-muted rounded-md p-6">
        <h2 className="text-xl font-semibold mb-4">Select Shops</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop A</h3>
              <p className="text-muted-foreground">123-456-7890</p>
            </div>
          </div>
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop B</h3>
              <p className="text-muted-foreground">987-654-3210</p>
            </div>
          </div>
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop C</h3>
              <p className="text-muted-foreground">555-555-5555</p>
            </div>
          </div>
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop D</h3>
              <p className="text-muted-foreground">111-222-3333</p>
            </div>
          </div>
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop E</h3>
              <p className="text-muted-foreground">444-444-4444</p>
            </div>
          </div>
          <div className="flex items-center bg-muted/20 rounded-md p-4">
            <Checkbox defaultChecked className="mr-4" />
            <div>
              <h3 className="font-medium">Shop F</h3>
              <p className="text-muted-foreground">999-999-9999</p>
            </div>
          </div>
        </div>
        <div className="mt-6 flex justify-end">
          <Button className="bg-primary text-primary-foreground">Send</Button>
        </div>
      </div>
    </div>)
  );
}
